[package]
name = "slug_intl"
version = "1.0.0-alpha.1"
edition = "2021"

[dependencies]
unicode-normalization = "0.1.23"
finl_unicode = {version = "1.2.0", features = ["categories"]}

[dev-dependencies]
urlencoding = "2.1.3"
